= Übung 7
Mctom Spdo
1.0.0, {docdate}: INSY
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:stylesheet: ../../asciidocs/css/dark.css

== Abfrage
Ausgabe der Spielernamen, die sowohl für das Team 1 als auch für das Team 2 gespielt
haben

[source, sql]
----
----

== Abfrage
NAME und INITIALS der Spieler, die 1980 keine Strafe erhalten haben

[source, sql]
----
----

== Abfrage
Ausgabe der Spieler, der mindestens eine Strafe über $80 erhalten haben

[source, sql]
----
----

== Abfrage
Ausgabe der Spieler, bei denen jede Strafe über $80 lag

[source, sql]
----
----

== Abfrage
Gesucht sind alle Mitarbeiter, deren Gehalt höher ist als das Durchschnittsgehalt ihrer
Abteilung

[source, sql]
----
----

== Abfrage
Ermittlung aller Abteilungen, die mindestens einen Mitarbeiter haben

[source, sql]
----
----

== Abfrage
Ausgabe aller Abteilungen, die mindestens einen Mitarbeiter aufweisen, der über 1000,-
verdient

[source, sql]
----
----

== Abfrage
Ausgabe aller Abteilungen, in der jeder Mitarbeiter mindestens 1000,- verdient

[source, sql]
----
----