= Übung 4
Mctom Spdo
1.0.0, {docdate}: ITP
ifndef::imagesdir[:imagesdir: images]
:icons: font
:sectnums:
:stylesheet: ../../css/dark.css

== Abfrage

Ausgabe von TEAMNO der Teams, in denen nicht der Spieler mit der Nummer 27 Kapitän ist

[source, sql]
----
select *
from TEAMS
where PLAYERNO != 27;
----

== Abfrage

Ausgabe von PLAYERNO, NAME und INITIALS der Spieler, die mindestens ein Match gewonnen haben

[source, sql]
----
select PLAYERNO, NAME, INITIALS
from PLAYERS
where PLAYERNO in (
    select PLAYERNO
    from MATCHES
    where WON >= 1);
----

== Abfrage

Ausgabe von SpielerNr und Name der Spieler, die mindestens eine Strafe erhalten haben

[source, sql]
----
select distinct PLAYERNO, NAME
from PLAYERS where PLAYERNO in (
    select distinct PLAYERNO
    from PENALTIES);
----

== Abfrage

Ausgabe von SpielerNr und Name der Spieler, die mindestens eine Strafe über 50.- erhalten haben

[source, sql]
----
select distinct PLAYERNO, NAME
from PLAYERS
where PLAYERNO in (
    select PLAYERNO
    from PENALTIES
    where AMOUNT > 50);
----

== Abfrage

Ausgabe von SpielerNr und Name der Spieler, die im selben Jahr wie R. Parmenter geboren sind

[source, sql]
----
select PLAYERNO, NAME
from Players
where YEAR_OF_BIRTH = (
    select YEAR_OF_BIRTH
    from PLAYERS
    where INITIALS = 'R' and NAME = 'Parmenter');
----

== Abfrage

Ausgabe von SpielerNr und Name des ältesten Spielers aus Stratford

[source, sql]
----
select PLAYERNO, NAME
from PLAYERS
where YEAR_OF_BIRTH = (
    select min(YEAR_OF_BIRTH)
    from PLAYERS);
----

== Abfrage

Gesucht sind alle Abteilungen, die keine Mitarbeiter beschäftigen

[source, sql]
----
select DEPTNO, DNAME
from DEPT
where DEPTNO not in(
    select distinct DEPTNO
    from EMP);
----

== Abfrage

Gesucht sind alle Mitarbeiter, die den gleichen Job wie JONES haben

[source, sql]
----
select * from EMP
where JOB = (
    select JOB
    from EMP
    where ENAME = 'JONES');
----

== Abfrage

Anzeigen aller Mitarbeiter, die mehr verdienen als irgendein Mitarbeiter aus Abteilung 30

[source, sql]
----
select EMPNO, ENAME
from EMP
where SAL > ANY(
    select sal
    from EMP
    where DEPTNO = 30);
----

.Original Solution
[%collapsible]
====

This is the original solution I came up with

[source, sql]
----
select *
from EMP
where SAL > (
    select * from (
        select SAL
        from EMP
        where DEPTNO = 30
        order by dbms_random.value)
    where rownum = 1);
----

====

== Abfrage

Anzeigen aller Mitarbeiter, die mehr verdienen als jeder Mitarbeiter aus Abteilung 30

[source,sql]
----
select *
from EMP
where SAL > (
    select max(SAL)
    from EMP
    where DEPTNO = 30);
----

== Abfrage

Anzeigen aller Mitarbeiter aus Abteilung 10, deren Job von keinem Mitarbeiter aus Abteilung 30 ausgeübt wird

[source,sql]
----
select *
from EMP
where DEPTNO = 10 and JOB not in(
    select distinct JOB
    from EMP
    where DEPTNO = 30);
----

== Abfrage

Gesucht sind die Mitarbeiterdaten (EMPNO, ENAME, JOB, SAL) des Mitarbeiters mit dem höchsten Gehalt

[source,sql]
----
select EMPNO, ENAME, JOB, SAL
from EMP
where SAL = (
    select max(SAL)
    from EMP);
----