= Test 01 B
Mctom Spdo
1.0.0, {docdate}: ITP
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:stylesheet: ../../asciidocs/css/dark.css

Für diese Übung benötigt man die Oracle Nordwind demo daten.

== Abfrage

Erstelle eine Liste aller Lieferanten mit ihren jeweils teuersten Produkten. Es sollen nur die Lieferanten ange-
zeigt werden, bei denen das teuerste Produkt billiger als 10 € ist.

[source, sql]
----
select SUPPLIERID, max(UNITPRICE)
from DEMO_NORTHWIND.PRODUCTS
group by SUPPLIERID
having max(UNITPRICE) < 10;
----

== Abfrage

Liste den Nachnamen des Mitarbeiters (employees) auf, der am längsten angestellt war.

[source, sql]
----
select LASTNAME, to_char(HIREDATE, 'DD.MM.YY')
from DEMO_NORTHWIND.EMPLOYEES
where months_between(SYSDATE, HIREDATE) = (
    select max(months_between(SYSDATE, HIREDATE))
    from DEMO_NORTHWIND.EMPLOYEES);
----

== Abfrage

Schreibe eine Abfrage, die alle Kundennamen ausgibt, die eine Bestellung aufgegeben haben, die Produkte
beinhaltet, die von einem Lieferanten aus Berlin geliefert werden. Weiters werden noch der Firmenname des
Lieferanten sowie die Anzahl der Bestellungen des Kunden bei dem jeweiligen Lieferanten angezeigt. Es soll
absteigend nach dem Kundennamen sortiert werden.

[source, sql]
----
select cust.CONTACTNAME, sup.COMPANYNAME , count(*) as "Anzahl Bestellungen" from DEMO_NORTHWIND.ORDERS od
join DEMO_NORTHWIND.ORDERDETAILS oddetails using (ORDERID)
join DEMO_NORTHWIND.PRODUCTS prod using (PRODUCTID)
join DEMO_NORTHWIND.SUPPLIERS sup using (SUPPLIERID)
join DEMO_NORTHWIND.CUSTOMERS cust using(CUSTOMERID)
where sup.CITY = 'Berlin'
group by sup.COMPANYNAME, cust.CONTACTNAME
order by cust.CONTACTNAME;
----

== Abfrage

Schreibe eine Abfrage, die alle Lieferanten ausgibt, die weniger als zwei verschiedene Produkte liefern. Ver-
wende hierzu einen Mengenoperator (UNION, MINUS oder INTERSECT)!

[source, sql]
----
select companyname
from DEMO_NORTHWIND.SUPPLIERS
minus
select COMPANYNAME
from DEMO_NORTHWIND.SUPPLIERS s
natural join DEMO_NORTHWIND.PRODUCTS
group by companyname
having count(*) >= 2;
----

== Abfrage

Wie heißt das teuerste Produkt eines Lieferanten aus Berlin? Verwende ausschließlich Subqueries

[source, sql]
----
select * from (
    select prod.PRODUCTNAME as productname, max(UNITPRICE) as maxprice
    from DEMO_NORTHWIND.PRODUCTS prod
    group by prod.PRODUCTNAME, prod.SUPPLIERID
        having prod.SUPPLIERID = (
            select sup2.SUPPLIERID
            from DEMO_NORTHWIND.SUPPLIERS sup2
            where sup2.CITY like 'Berlin')
    order by maxprice desc)
where rownum = 1;
----
