= Übung 13
Mctom Spdo
1.0.0, {docdate}: INSY
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:stylesheet: ../../asciidocs/css/dark.css

== Schema

Erstelle das Datenbank-Schema für die unten angegebenen Tabellen. Erzeuge bei
den CREATE TABLE-Statements auch die entsprechenden Primär- und Fremd-
schlüssel-Constraints. Erstellen Sie ein Skript, das ein wiederholtes Anlegen der Ta-
bellen ermöglicht. Erstellen Sie weiters ein "DROP-Skript" zum automatischen Löschen der Tabellen.

Relationenschemata:

Teil (TNr, Bezeichnung, Art, Lagerstand, Mengeneinheit) +
Artikel (TNr, Verkaufspreis) +
Fremdteil (TNr, Bestellpolitik) +
Eigenteil (TNr, Losgroesse) +
Struktur (OberTNr, UnterTNr, Menge) +
Arbeitsplan (APNr, Ersteller, ErstellDatum, TNr) +
Arbeitsgang (APNr, AGNr, VNr) +
TechnischesVerfahren (VNr, Bezeichnung) +
Betriebsmittel (BMNr, Bezeichnung, Wartung) +
AG_BM_Zuordnung (APNr, AGNr, BMNR, Ruestzeit, Arbeitszeit) +
AG_Komp_Zuordnung (APNr, AGNr, TNr, Menge) +

[plantuml,sceme]
----
include::uebung13.puml[]
----
