@startuml

!theme plain

skinparam backgroundColor transparent
skinparam monochrome reverse

left to right direction

class Teil {
    - <u>TNr</u>
    ---
    - Bezeichnung
    - Art
    - Lagerstand
    - Mengeneinheit
}

class Artikel {
    - <u>TNr</u>
    ---
    - Verkaufspreis
}

class Fremdteil {
    - <u>TNr</u>
    ---
    - Bestellpolitik
}

class Eigenteil {
    - <u>TNr</u>
    ---
    - Losgrösse
}

class Struktur {
    - <u>OberTNr</u>
    - <u>UnterTNr</u>
    ---
    - Menge
}

class Arbeitsplan {
    - <u>APNr</u>
    ---
    - Ersteller
    - ErstellDatum
    - TNr (reference)
}

class Arbeitsgang {
    - <u>AGNr</u>
    ---
    - <u>APNr</u> (reference)
    - Vnr (reference)
}

class TechnischesVerfahren {
    - <u>VNr</u>
    ---
    - Beizeichnung
}

class Betriebsmittel {
    - <u>BMNr</u>
    ---
    - Bezeichnung
    - Wartung
}

class AG_BM_Zuordnung {
    - <u>APNr</u> (reference)
    - <u>AGNr</u> (reference)
    - <u>BMNr</u> (reference)
    ---
    - Ruhezeit
    - Arbeitszeit
}

class AG_Komp_Zuordnung {
    - <u>APNr</u> (reference)
    - <u>AGNr</u> (reference)
    - <u>TNr</u> (reference)
    ----
    - Menge
}

Teil "1"--"*" Eigenteil
Teil "1"--"*" Fremdteil
Teil "1"--"*" Artikel
Teil "2"--"*" Struktur
Teil "1"--"*" Arbeitsplan
Teil "1"--"*" AG_BM_Zuordnung
Teil "1"--"*" AG_Komp_Zuordnung

Arbeitsplan "1"--"*" Arbeitsgang
Arbeitsplan -- AG_Komp_Zuordnung
Arbeitsplan -- AG_BM_Zuordnung
AG_Komp_Zuordnung -- Arbeitsgang

AG_BM_Zuordnung "*"--"1" Betriebsmittel
AG_BM_Zuordnung  -- Arbeitsgang


Arbeitsgang "*"--"1" TechnischesVerfahren

@enduml