= Übung 12
Mctom Spdo
1.0.0, {docdate}: INSY
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:stylesheet: ../../asciidocs/css/dark.css

== Erstelle die Tabelle PKT

[cols=2]
|===

|PK
|numerisch, 3 Stellen, Primärschlüssel

|C1
|alphanumerisch, 20 Stellen, 1. Stelle muss A oder F sein

|C2
|numerisch, 3 Vorkommastellen, 1 Nachkommastelle, Werte zwischen 0.0 und 199.9 erlaubt

|===

[source, sql]
----
create table PKT (
    PK number(3) primary key,
    C1 varchar(20),
    C2 decimal(3, 1),
    constraint c1_first_letter check(C1 like 'A%' or C1 like 'F%'),
    constraint c2_between check(C2 >= 0.0 and C2 <= 199.9)
);
----

== Erstelle die Tabelle FKT mit

[cols=2]
|===

|PK1
|numerisch, 2 Stellen

|PK2
|numerisch, 1 Stelle, Primärschlüssel (PK1,PK2)

|C1
|Datum

|C2
|alphanumerisch, 1 Stelle. Es sind nur die Werte 'J' und 'N' erlaubt

|FK
|numerisch, 3 Stellen, Fremdschlüssel, verweist auf PKT,
wird ein Satz in PKT gelöscht, so sollen alle entsprechenden Sätze aus
FKT automatisch mitgelöscht werden

|===

[source, sql]
----
create table FKT (
    PK1 number(2),
    PK2 number(1),
    C1 date,
    C2 varchar(1),
    FK number(3),
    constraint primary_key PRIMARY KEY (PK1, PK2),
    constraint C2_yes_no check(C2 = 'J' or C2 = 'N'),
    constraint fkt_pkt foreign key (FK) references PKT on delete cascade
);
----

== Löschen der Integritätsbedingung auf C1 in PKT

[source, sql]
----
alter table PKT drop constraint C1_FIRST_LETTER;
----

== Löschen der beiden Tabellen

[source, sql]
----
drop table FKT;
drop table PKT;
----

== Schulungsinstitut

Ein Schulungsinstitut veranstaltet Kurse. Aus didaktischen und platztechnischen
Gründen wird lediglich eine bestimmte Höchstteilnehmerzahl zugelassen (als Stan-
dard wird der Wert 15 vorgesehen). Um den Schulungserfolg weitgehend zu sichern
bzw. eine homogene Teilnehmergruppe sicherzustellen, sind für die Teilnahme an
bestimmten Kursen Voraussetzungskurse Bedingung (es kann davon ausgegangen
werden, dass 1 Voraussetzungskurs hinreichend ist).
Jeder Kurs wird mehrmals veranstaltet - wobei jede Kursveranstaltung von unter-
schiedlichen Referenten abgewickelt werden kann. Jede Kursveranstaltung wird ge-
sondert beurteilt (Schulnoten!)


* Zeichne das ERD
* Wandle das ERD in ein relationales Modell um und erstelle ein Script der CREATE TABLES mit den notwendigen Constraints.
* Teste das System durch Eingabe von Datensätzen.
* Lösche die Tables


=== ERD

[plantuml, 5-schulungsinstut]
----
@startuml

left to right direction
!theme plain

class Kurs {
- maxPeople: number(15)
---
- voraussetzung: Kurs
}

class Teilnehmer {
- ID
- name: varchar
}

class Kursveranstaltung {
}

class Teilnahme {
- note: number (1 - 5)
}

class Referent {}

Kurs -- Kurs
Kurs "*"--"*" Kursveranstaltung
(Kurs, Kursveranstaltung) .. Kurs_Kursveranstaltung

Kursveranstaltung "*" -- "*" Teilnehmer
(Kursveranstaltung, Teilnehmer) .. Teilnahme
Kursveranstaltung -- Referent

@enduml
----

Lösung des Lehrers:

[plantuml, 5-schulinstitut-solution]
----

left to right direction

!theme plain

class Kurs {
}

class Referent {
}

class Veranstaltung {
}

class Teilnehmner{}

Kurs "1" -- "*" Veranstaltung
Veranstaltung "*" -- "*" Teilnehmner
(Teilnehmner, Veranstaltung) .. Veranstaltung_Teilnehmeer
Veranstaltung "*" -- "*" Referent
(Veranstaltung, Referent) .. Teilnahme
Kurs "0..1" -- "1" Kurs
----

=== RM

* Kurs(KID, SKID, Maximal, Name)
* Veranstaltung(VID, Name, KID, Datum)

=== Create tables

[source, sql]
----
create table KURS (
    KID number primary key,
    SKID number,
    NAME varchar(30),
    constraint fkt_SKID foreign key (SKID) references KURS
);

create table VERANSTALTUNG(
    VID number primary key,
    NAME varchar(30),
    KID number,
    DATUM date,
    constraint fkt_KID foreign key (KID) references KURS
);
----

TODO: finish